name: Linking-entities-by-immutable-column

services:
  database:
    image: postgres:17.4
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes:
      - ./create_db_and_schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/postgres/database:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network: