spring:
  datasource:
    password: pass
    username: postgres
    url: jdbc:postgresql://localhost:5435/linking_entities_by_immutable_column
    hikari:
      schema: test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: test

